language: ruby
rvm:
  - ruby-1.8.7-head
  - ruby-1.9.2-p330
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - ree-1.8.7-2011.12
before_install: # https://github.com/travis-ci/travis-ci/issues/5239
  - gem install bundler
matrix:
  fast_finish: true
  allow_failures:
  - rvm: ree-1.8.7-2011.12
  